import Head from 'next/head';
import Countdown from '../components/Countdown';

export default function Home() {
	return (
		<>
			<Head>
				<title>PREMIER FARMERS MART</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Countdown releaseDate="2023-01-21" />
			</main>
		</>
	);
}
